Numpy 

Numpy is fundamental library for scientific computing in python.It provides support for arrays and metrics, along with a collection of methatical functions to operate on these data structures. In this lesson,we will cover the basics of Numpy, focusing onn arrays and vectorized operations

In [20]:
import numpy as np
!pip install numpy
##create array using numpy 
##create a 1D array 

arry1=np.array([1,2,3,4,5,6])
print(arry1)
print(type(arry1))
print(arry1.shape)


[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) ##1 row and 5 columns 



array([[1, 2, 3, 4, 5]])

In [9]:
##
arr2=np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [4 5 6 7 8]]
(2, 5)


In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
##identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
##Identity matrix 
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
arr=np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("Size (number of elements)",arr.size)
print("Data types:",arr.dtype)
print("Item size (in bytes)",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements) 6
Data types: int64
Item size (in bytes) 8


In [31]:
##nmpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
##Elements Wise addition
print("addition:",arr1+arr2)
print("substraction",arr1-arr2)
print("multiplication",arr1*arr2)
print("divisiion",arr1/arr2)
arr2.reshape(1,5)

addition: [11 22 33 44 55]
substraction [ -9 -18 -27 -36 -45]
multiplication [ 10  40  90 160 250]
divisiion [0.1 0.1 0.1 0.1 0.1]


array([[10, 20, 30, 40, 50]])

In [ ]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
arr2.shape ##1 row and 5 columns 


##Universal function
arr=np.array([2,3,4,5,6])

##square  root 
print(np.sqrt(arr))

##Exponantial 
print(np.exp(arr))


(2, 5)

In [26]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [27]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
##identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
##Universal functions(ufuncs) 
##array slicing and Indexing problem

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)



Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
arr[0]

array([1, 2, 3, 4])

In [34]:
arr[2:]

array([[ 9, 10, 11, 12]])

In [36]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [37]:
print(arr[0][0])
print(arr[0:2,1:])

1
[[2 3 4]
 [6 7 8]]


In [38]:
##modify array elements 
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [39]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [40]:
##statitical concepts ---Normalization 
##to have mean of 0 and standard deviation of 1 
data=np.array([1,2,3,4,5])

##calculate the mean adn standard deviation 
mean=np.mean(data)
std_dev=np.std(data)

#normalize the data 
normalized_data=(data-mean)/std_dev
print('normalized data:',normalized_data)

normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [41]:
data=np.array([1,2,3,4,5,6,7,8,910])
#mean
mean=np.mean(data)
print("Mean:",mean)

#median 
median=np.median(data)
print("Median:",median)
##standard deviation 
std_dev=np.std(data)
print("Standard Deviation:",std_dev)

#varience 
variance=np.var(data)
print("Variance:",variance)


Mean: 105.11111111111111
Median: 5.0
Standard Deviation: 284.5793950706295
Variance: 80985.43209876544


In [46]:
#Logical operation 
data=np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>5) & (data<=8)]

array([6, 7, 8])